export enum errConstants {
  ERR_CLIENT_NAME_EMPTY = 'ERR_CLIENT_NAME_EMPTY',
  ERR_CLIENT_CALLBACK_URL_EMPTY = 'ERR_CLIENT_CALLBACK_URL_EMPTY',
  ERR_CLIENT_DUPLICATED = 'ERR_CLIENT_DUPLICATED',
  ERR_CLIENT_NOT_FOUND = 'ERR_CLIENT_NOT_FOUND',
}
